version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
